apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: nodejs-deployment
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: teodora95/node-helloworld
        ports:
        - containerPort: 80
       
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: nodejs-service
  labels:
    app: helloworld
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32121
  selector:
    app: helloworld
