apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-helloworld-deployment
  labels:
    app: nodejs-helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-helloworld
  template:
    metadata:
      labels:
        app: nodejs-helloworld
    spec:
      containers:
      - name: nodejs-helloworld
        image: teodora95/nodejs-helloworld-repo:latest
        ports:
        - containerPort: 80
        

apiVersion: v1
kind: Service
metadata:
  name: nodejs-helloworld-service
  namespace: kube-system
  labels:
    app: nodejs-helloworld
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
      app: nodejs-helloworld
  type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: nodejs-helloworld-clusterip-service
  namespace: kube-system
  labels:
    app: nodejs-helloworld
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
      app: nodejs-helloworld
  type: ClusterIP

apiVersion: v1
kind: Service
metadata:
  name: nodejs-helloworld-lb-service
  namespace: kube-system
  labels:
    app: nodejs-helloworld
spec:
  selector:
    app: nodejs-helloworld
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80

apiVersion: v1
kind: Service
metadata:
  name: nodejs-helloworld-my-xn-service
  namespace: kube-system
  labels:
    app: nodejs-helloworld
spec:
  type: ExternalName
  externalName: nodejshelloworldexternal.com
