apiVersion: v1
kind: Service
metadata:
  name: nodejs-helloworld-clusterip-service
  namespace: kube-system
  labels:
    app: nodejs-helloworld
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
      app: nodejs-helloworld
  type: ClusterIP