apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-helloworld-deployment
  labels:
    app: nodejs-helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-helloworld
  template:
    metadata:
      labels:
        app: nodejs-helloworld
    spec:
      containers:
      - name: nodejs-helloworld
        image: teodora95/nodejs-helloworld-repo:1.0.0
        ports:
        - containerPort: 80
---        

apiVersion: v1
kind: Service
metadata:
  name: nodejs-helloworld-service
  namespace: kube-system
  labels:
    app: nodejs-helloworld
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
      app: nodejs-helloworld
  type: NodePort

